In [2]:
import warnings
warnings.filterwarnings('ignore')
import os 
import pandas as pd

In [14]:
input_data = pd.read_csv('/home/mehrsa/data_works/RBC_results/ER_tests/data_files/cbd_test_case_Y.csv', dtype = object)

#### INPUT sample:

In [15]:
input_data.head(2)

,source_title,corporation_number,business_number,business_name,alternate_name,category,subcategory,description,location_address_source,location_street_address,...,mailing_postal_code,mailing_country,mailing_geometry,telephone,fax,email,url,modified_at,retrieved_at,source_url
0,SEDAR,NaN,NaN,Yaletown Capital Corp.,NaN,other,NaN,NaN,"Unit 120 - 21320 Gordon Way Richmond, British ...",21320 Gordon Way,...,V6W 1J8,Canada,POINT (-122.9864387 49.1670515),604 270-0800,NaN,douglaskind@freedombionics.com,NaN,NaN,2018-09-05,http://www.sedar.com/DisplayProfile.do?lang=EN...
1,SEDAR,NaN,NaN,Yaletown Energy Capital Corp.,NaN,other,NaN,NaN,"#210 - 1682 W 7th Avenue Vancouver, British Co...",1682 West 7th Avenue,...,V6J 4S6,Canada,POINT (-123.1427874 49.2651792),604 512-0101,NaN,emil@temmgmt.com,NaN,NaN,2018-09-05,http://www.sedar.com/DisplayProfile.do?lang=EN...

#### 1- clean and preprocess data based on config file

In [16]:
!sudo python prep_columns_for_er.py

#### sample of intermediate cleaned data for resolver process

In [19]:
cleaned_input_data = pd.read_csv('/home/mehrsa/data_works/RBC_results/ER_tests/data_files/cbd_test_case_Y_sub_cleaned.csv', dtype = object)

In [20]:
cleaned_input_data.head(2)

,business_name,location_address_source,cleaned_business_name,cleaned_location_address_source
0,Yaletown Capital Corp.,"Unit 120 - 21320 Gordon Way Richmond, British ...",yaletown capital,unit 120 21320 gordon way richmond british col...
1,Yaletown Energy Capital Corp.,"#210 - 1682 W 7th Avenue Vancouver, British Co...",yaletown energy capital,210 1682 w 7th avenue vancouver british columb...

#### 2- Run resolvER process with the same config file

In [21]:
!sudo python resolver_flow.py

Loading the embedding model.
Embedding model loaded --- 15.6474080086 seconds ---
--- 0.0719590187073 seconds (Values were tokenized) ---
--- 1.38662791252 seconds --- (All values were encoded)
--- 0.230940103531 seconds --- (Weighted average embeddings computed)
--- 0.172111034393 seconds (Vectors were added to the index) ---
--- 1.17400097847 seconds (Index tree was built) ---
Index tree have been saved.
One dataset values have been provided -- switched to dedupe mode --
('number of iterations: ', 2)
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process started
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
New process finished
All processes for 0 are done.
New process started
New process finished
All processes for 1 are done.
All processes for all iterations are done.
Time taken
25.8746709824
Resolving is done... --- 47.6066720486 seconds ---
Saving results ...
Results have been saved.

#### intermediate results: - Cluster ID per row, Score per row ...

In [26]:
clusters = pd.read_csv('/home/mehrsa/data_works/RBC_results/ER_tests/intermediate_files/clusters_res_cbd_test_case_Y.csv')
scores = pd.read_csv('/home/mehrsa/data_works/RBC_results/ER_tests/intermediate_files/cluster_scores_cbd_test_case_Y.csv')
res_frame = pd.concat([clusters, scores], axis = 1)

In [27]:
res_frame

          clusts     0     1
0     N2MRFMKBW6  1.00  1.00
1     ZL4H5E4J07  1.00  1.00
2     3X7XZVA7FE  1.00  1.00
3     48P58G3ZJS  1.00  1.00
4     50UMGXZ87O  1.00  1.00
5     XL0ZQHZMYF  1.00  1.00
6     TEB8R77Z0X  1.00  1.00
7     TEB8R77Z0X  1.00  1.00
8     HM6Y0ZK8V0  1.00  1.00
9     1MBENRCQ51  1.00  1.00
10    OCFZJWK1XZ  1.00  1.00
11    QVISWFYJMO  1.00  1.00
12    FNGOTJS0Y5  1.00  1.00
13    G82J7S5N54  1.00  1.00
14    KIT08TMY2P  1.00  1.00
15    6D9CSYN2MM  1.00  1.00
16    DEERC8D684  1.00  1.00
17    GSCZMC0IWP  1.00  1.00
18    HPS8QNBS2P  1.00  1.00
19    KZ4AWQ3HQC  1.00  1.00
20    PIEXBARAVZ  1.00  1.00
21    0S4TGNOOH1  1.00  1.00
22    EIB3KSA5WT  1.00  1.00
23    HHOYLYI6LV  1.00  1.00
24    6ZCXKSVYH6  1.00  1.00
25    I51ZY3WE65  1.00  1.00
26    HC6YJ8YT6T  1.00  1.00
27    SJVAO1U6GJ  1.00  1.00
28    3YJCPSEZTJ  1.00  1.00
29    MYZ5OX6T8E  1.00  1.00
...          ...   ...   ...
6951  T6IJLTKRCC  1.00  1.00
6952  IY3TGLKZ2Q  1.00  1.00
6953  0HYVRWMK9C  1.00  1.00
6954  0HYVRWMK9C  0.98  0.85
6955  BIOQ3ZNIG6  1.00  1.00
6956  5VPWB5YPBA  1.00  1.00
6957  WJ4S8BOVIK  1.00  1.00
6958  CC2PEVU797  1.00  1.00
6959  J72FMMS3BT  1.00  1.00
6960  7L3W1Q4QLP  1.00  1.00
6961  YX0LI1CVQ3  1.00  1.00
6962  K52XK430C3  1.00  1.00
6963  22NWHTJ1TB  1.00  1.00
6964  6GTY6URWNI  1.00  1.00
6965  7LGND5TMPH  1.00  1.00
6966  PU26GTVNW4  1.00  1.00
6967  9U6EZLSXF0  1.00  1.00
6968  FUSJU15JAI  1.00  1.00
6969  Y4YKL3W421  1.00  1.00
6970  4AL0NNKHWA  1.00  1.00
6971  BIPH9C0PP7  1.00  1.00
6972  X0RKZEWXX5  1.00  1.00
6973  85ZV1QER49  1.00  1.00
6974  MF5ALSIJY4  0.93  0.64
6975  WPD3NENFLO  1.00  1.00
6976  Y4HZ6MD42I  1.00  1.00
6977  OCLGV4M4QC  1.00  1.00
6978  9AL307OD8R  0.91  0.55
6979  IH15I048BA  1.00  1.00
6980  R8E0237JJ8  1.00  1.00

[6981 rows x 3 columns]

#### to obtain final results, a custom pipeline should be run to recreate the original frame:

In [28]:
!sudo python dedupe_data.py

Datasets loaded
Resolver results loaded
Deduped dataset was saved.

#### OUTPUT: final results:

In [29]:
fin_frame = pd.read_csv('/home/mehrsa/data_works/RBC_results/ER_tests/data_files/cbd_test_case_Y_deduped.csv',
                        dtype = object)

#### a sample cluster:

In [33]:
fin_frame[fin_frame.clusts == '0S4TGNOOH1']

,Unnamed: 0,source_title,corporation_number,business_number,business_name,alternate_name,category,subcategory,description,location_address_source,...,email,url,modified_at,retrieved_at,source_url,cleaned_business_name,cleaned_location_address_source,clusts,0,1
21,21,SEDAR,NaN,NaN,Yellow Media Inc.,NaN,communications and media,publishing and printing,NaN,"16 Place du Commerce Ile des Soeurs Verdun, Qu...",...,www.ypg.com,NaN,NaN,2018-09-05,http://www.sedar.com/DisplayProfile.do?lang=EN...,yellow media,16 place du commerce ile des soeurs verdun que...,0S4TGNOOH1,1.0,1.0
1378,1378,CC,4339959.0,855979688RC0002,Yellow Media Inc. -,Yellow MÃ©dia inc.,NaN,NaN,NaN,"16 PLACE DU COMMERCE, ILE DES SOEURS VERDUN Qu...",...,NaN,NaN,2018-06-19,2018-09-05,https://www.ic.gc.ca/app/scr/cc/CorporationsCa...,yellow media,16 place du commerce ile des soeurs verdun que...,0S4TGNOOH1,1.0,0.83
1379,1379,CC,4339959.0,855979688RC0002,Yellow MÃ©dia inc.,Yellow MÃ©dia inc.,NaN,NaN,NaN,"16 PLACE DU COMMERCE, ILE DES SOEURS VERDUN Qu...",...,NaN,NaN,2018-06-19,2018-09-05,https://www.ic.gc.ca/app/scr/cc/CorporationsCa...,yellow media,16 place du commerce ile des soeurs verdun que...,0S4TGNOOH1,1.0,0.83
2065,2065,CC,8254320.0,802618884RC0001,Yellow Media Limited,Yellow MÃ©dia LimitÃ©e,NaN,NaN,NaN,16 Place du Commerce Verdun Quebec H3E 2A5 Canada,...,NaN,NaN,2018-06-19,2018-09-05,https://www.ic.gc.ca/app/scr/cc/CorporationsCa...,yellow media,16 place du commerce verdun quebec h3e 2a5 canada,0S4TGNOOH1,1.0,1.0